name: publish

on:
  push:
    tags:
      - v[0-9]*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cabal sdist
      - uses: sol/hackage-publish@dev
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          publish: true
